### ISSUE TITLE
Error when updating to php 8.0

### ISSUE THREAD

**Issue by meaz** [mstilkerich/rcmcarddav#375]
I have roundcube 1.5.2 + carddav installed with php 7.3.

When I update to php 8.0, and do `php8.0 composer.phar update  roundcube/carddav` I get this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpspec/prophecy v1.10.3 requires php ^5.3|^7.0 -> your php version (8.0.15) does not satisfy that requirement.
    - phpunit/phpunit 4.8.36 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[v1.10.3].
    - phpunit/phpunit is locked to version 4.8.36 and an update of this package was not requested.
```
Is carddav compatible with php 8.0?

**Comment by mstilkerich** [comment]
Yes it is. I wonder which package requires the very old phpunit version, definitely not rcmcarddav. Please try running composer with the option `—no-dev` to skip development dependencies like phpunit, this might get you around the problem.

```
composer.phar update --no-dev
```

**Comment by mstilkerich** [comment]
Guess this is resolved for you?! If not please reopen.

**Comment by meaz** [comment]
Hi,

I'm sorry it took me so long to answer. Actually I still have the issue. Not only when updating from 7.4 to 8.0, but even if I install roundcube latest from scratch, then install carddav with `php8.0 composer.phar require --update-no-dev roundcube/carddav`. I get this:
```
Using version ^4.3 for roundcube/carddav
./composer.json has been updated
Running composer update roundcube/carddav
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpspec/prophecy v1.10.3 requires php ^5.3|^7.0 -> your php version (8.0.19) does not satisfy that requirement.
    - phpunit/phpunit 4.8.36 requires phpspec/prophecy ^1.3.1 -> satisfiable by phpspec/prophecy[v1.10.3].
    - phpunit/phpunit is locked to version 4.8.36 and an update of this package was not requested.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require roundcube/carddav:*" to figure out if any version is installable, or "composer require roundcube/carddav:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I have no issue if I install carddav on a php7.4 environment.

**Comment by mstilkerich** [comment]
Hello, please try running a composer update first to adapt the dependencies includes with the roundcube package to be compatible to php8, then install rcmccarddav. Example:

```
$ tar xzf roundcubemail-1.5.2-complete.tar.gz
$ cd roundcubemail-1.5.2
$ composer update --no-dev
roundcube/plugin-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "roundcube/plugin-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 15 updates, 5 removals
  - Removing paragonie/random_compat (v2.0.20)
  - Removing phpdocumentor/reflection-common (1.0.1)
  - Removing phpdocumentor/type-resolver (0.3.0)
  - Removing symfony/polyfill-php70 (v1.19.0)
  - Removing webmozart/assert (1.9.1)
  - Upgrading doctrine/instantiator (1.0.5 => 1.4.1)
  - Upgrading guzzlehttp/guzzle (6.5.5 => 6.5.6)
  - Upgrading guzzlehttp/psr7 (1.8.3 => 1.8.5)
  - Upgrading pear/crypt_gpg (v1.6.6 => v1.6.7)
  - Downgrading phpdocumentor/reflection-docblock (3.2.2 => 2.0.5)
  - Downgrading phpspec/prophecy (v1.10.3 => v1.5.0)
  - Downgrading phpunit/php-timer (1.0.9 => 1.0.8)
  - Upgrading ralouphie/getallheaders (2.0.5 => 3.0.3)
  - Downgrading sebastian/diff (1.4.3 => 1.4.1)
  - Downgrading sebastian/environment (1.3.8 => 1.3.7)
  - Upgrading symfony/polyfill-ctype (v1.19.0 => v1.25.0)
  - Upgrading symfony/polyfill-intl-idn (v1.19.0 => v1.25.0)
  - Upgrading symfony/polyfill-intl-normalizer (v1.19.0 => v1.25.0)
  - Upgrading symfony/polyfill-php72 (v1.19.0 => v1.25.0)
  - Upgrading symfony/yaml (v2.8.52 => v3.4.47)
Writing lock file
Installing dependencies from lock file
Package operations: 0 installs, 7 updates, 2 removals
  - Removing symfony/polyfill-php70 (v1.19.0)
  - Removing paragonie/random_compat (v2.0.20)
  - Upgrading symfony/polyfill-php72 (v1.19.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-intl-normalizer (v1.19.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-intl-idn (v1.19.0 => v1.25.0): Extracting archive
  - Upgrading ralouphie/getallheaders (2.0.5 => 3.0.3): Extracting archive
  - Upgrading guzzlehttp/psr7 (1.8.3 => 1.8.5): Extracting archive
  - Upgrading guzzlehttp/guzzle (6.5.5 => 6.5.6): Extracting archive
  - Upgrading pear/crypt_gpg (v1.6.6 => v1.6.7): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
$ composer require --update-no-dev 'roundcube/carddav:^4.3'
./composer.json has been updated
Running composer update roundcube/carddav
Loading composer repositories with package information
Updating dependencies
Lock file operations: 7 installs, 0 updates, 0 removals
  - Locking mstilkerich/carddavclient (v1.2.1)
  - Locking psr/http-client (1.0.1)
  - Locking psr/log (1.1.4)
  - Locking roundcube/carddav (v4.3.0)
  - Locking sabre/uri (2.2.2)
  - Locking sabre/vobject (4.4.1)
  - Locking sabre/xml (2.2.5)
Writing lock file
Installing dependencies from lock file
Package operations: 7 installs, 0 updates, 0 removals
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing sabre/uri (2.2.2): Extracting archive
  - Installing sabre/xml (2.2.5): Extracting archive
  - Installing sabre/vobject (4.4.1): Extracting archive
  - Installing mstilkerich/carddavclient (v1.2.1): Extracting archive
Deprecation Notice: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /tmp/roundcubemail-1.5.2/program/lib/Roundcube/rcube.php:837
Deprecation Notice: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /tmp/roundcubemail-1.5.2/program/lib/Roundcube/bootstrap.php:329
  - Installing roundcube/carddav (v4.3.0): Extracting archive
 0/7 [>---------------------------]   0%Creating package config file
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by meaz** [comment]
Thanks a lot, that was it. Really kind of you that you answered so fast.
