### ISSUE TITLE
Uncaught Error: Interface "MStilkerich\RCMCardDAV\Frontend\RcmInterface" not found

### ISSUE THREAD

**Issue by amessina** [mstilkerich/rcmcarddav#415]
Following https://github.com/mstilkerich/rcmcarddav/blob/master/doc/INSTALL.md#installation-from-release-tarball and adding this plugin to a Fedora 37 RPM installation of RoudCubeMail, the following error is thrown.  The previous install of 4.4.6 works without a hitch.  I have upgraded the configuration for the changes in this version.

PHP Fatal error:  Uncaught Error: Interface "MStilkerich\RCMCardDAV\Frontend\RcmInterface" not found in /usr/share/roundcubemail/plugins/carddav/carddav.php:35
Stack trace:
#0 /usr/share/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(204): include()
#1 /usr/share/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(126): rcube_plugin_api->load_plugin()
#2 /usr/share/roundcubemail/program/include/rcmail.php(108): rcube_plugin_api->load_plugins()
#3 /usr/share/roundcubemail/program/include/rcmail.php(86): rcmail->startup()
#4 /usr/share/roundcubemail/index.php(43): rcmail::get_instance()
#5 {main}
  thrown in /usr/share/roundcubemail/plugins/carddav/carddav.php on line 35

**Comment by mstilkerich** [comment]
Hello,

 thanks for reporting this. In v5 the carddav root class depends on an interface part of RCMCardDAV, therefore this interface must be findable by PHP before the class is declared. Up to now, the additional autoloader for the tarball-based installation would only be loaded in the constructor of the class, which is too late. I have now moved it outside the class in the referenced commit. Please see if it fixes the issue for you.

I did try the tarball, however I used my main test roundcube installation where I previously installed RCMCardDAV using composer, which is why the interface could already be found using the primary autoloader of roundcube and I thus did not notice the issue.

I have pulled the 5.0.0 tarball and added a note in the release notes that no tarball for 5.0.0 is available because of this issue. I will wait a bit if other issues pop up before releasing a 5.0.1 with a new tarball.

**Comment by amessina** [comment]
Thank you @mstilkerich for such a rapid fix.  I confirm 4558a10933112c1e57c79632a69216cbc9e92b7d works perfectly here.

**Comment by mstilkerich** [comment]
5.0.1 is out and should fix the issue with the tarball.

**Comment by pipip** [comment]
I still have the issue with 5.0.1

I installed via composer:
`composer \
        --working-dir=/usr/src/roundcubemail/ \
        --prefer-dist \                                                                                    --prefer-stable \
        --update-no-dev \
        --with-all-dependencies \                                                                          --no-interaction \
        --optimize-autoloader \                                                                            require \
            johndoh/contextmenu \                                                                              elm/identity_smtp:dev-master \
            roundcube/carddav \                                                                                germancoding/tls_icon:dev-master \
            #texxasrulez/persistent_login \                                                                    dsoares/removeattachments \`

Error
`[php:error] [pid 133] [client x.x.x.x] PHP Fatal error:  Uncaught Error: Interface "MStilkerich\RCMCardDAV\Frontend\RcmInterface" not found in /var/www/html/plugins/carddav/carddav.php:42\nStack trace:\n#0 /var/www/html/program/lib/Roundcube/rcube_plugin_api.php(204): include()\n#1 /var/www/html/program/lib/Roundcube/rcube_plugin_api.php(126): rcube_plugin_api->load_plugin('carddav')\n#2 /var/www/html/program/include/rcmail.php(108): rcube_plugin_api->load_plugins(Array, Array)\n#3 /var/www/html/program/include/rcmail.php(86): rcmail->startup()\n#4 /var/www/html/index.php(43): rcmail::get_instance(0, NULL)\n#5 {main}\n  thrown in /var/www/html/plugins/carddav/carddav.php on line 42`
